// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auto_increment.proto

package auto_increment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSingleRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleRequest) Reset()         { *m = GetSingleRequest{} }
func (m *GetSingleRequest) String() string { return proto.CompactTextString(m) }
func (*GetSingleRequest) ProtoMessage()    {}
func (*GetSingleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c5cff9d1a655ea, []int{0}
}

func (m *GetSingleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleRequest.Unmarshal(m, b)
}
func (m *GetSingleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleRequest.Marshal(b, m, deterministic)
}
func (m *GetSingleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleRequest.Merge(m, src)
}
func (m *GetSingleRequest) XXX_Size() int {
	return xxx_messageInfo_GetSingleRequest.Size(m)
}
func (m *GetSingleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleRequest proto.InternalMessageInfo

func (m *GetSingleRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetSingleResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleResponse) Reset()         { *m = GetSingleResponse{} }
func (m *GetSingleResponse) String() string { return proto.CompactTextString(m) }
func (*GetSingleResponse) ProtoMessage()    {}
func (*GetSingleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c5cff9d1a655ea, []int{1}
}

func (m *GetSingleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleResponse.Unmarshal(m, b)
}
func (m *GetSingleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleResponse.Marshal(b, m, deterministic)
}
func (m *GetSingleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleResponse.Merge(m, src)
}
func (m *GetSingleResponse) XXX_Size() int {
	return xxx_messageInfo_GetSingleResponse.Size(m)
}
func (m *GetSingleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleResponse proto.InternalMessageInfo

func (m *GetSingleResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetSingleResponse) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetMultipleRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Quantity             uint64   `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleRequest) Reset()         { *m = GetMultipleRequest{} }
func (m *GetMultipleRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleRequest) ProtoMessage()    {}
func (*GetMultipleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c5cff9d1a655ea, []int{2}
}

func (m *GetMultipleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleRequest.Unmarshal(m, b)
}
func (m *GetMultipleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleRequest.Merge(m, src)
}
func (m *GetMultipleRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleRequest.Size(m)
}
func (m *GetMultipleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleRequest proto.InternalMessageInfo

func (m *GetMultipleRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetMultipleRequest) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type GetMultipleResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []uint64 `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleResponse) Reset()         { *m = GetMultipleResponse{} }
func (m *GetMultipleResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleResponse) ProtoMessage()    {}
func (*GetMultipleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c5cff9d1a655ea, []int{3}
}

func (m *GetMultipleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleResponse.Unmarshal(m, b)
}
func (m *GetMultipleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleResponse.Merge(m, src)
}
func (m *GetMultipleResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleResponse.Size(m)
}
func (m *GetMultipleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleResponse proto.InternalMessageInfo

func (m *GetMultipleResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetMultipleResponse) GetValue() []uint64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSingleRequest)(nil), "GetSingleRequest")
	proto.RegisterType((*GetSingleResponse)(nil), "GetSingleResponse")
	proto.RegisterType((*GetMultipleRequest)(nil), "GetMultipleRequest")
	proto.RegisterType((*GetMultipleResponse)(nil), "GetMultipleResponse")
}

func init() { proto.RegisterFile("auto_increment.proto", fileDescriptor_59c5cff9d1a655ea) }

var fileDescriptor_59c5cff9d1a655ea = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0x2d, 0xc9,
	0x8f, 0xcf, 0xcc, 0x4b, 0x2e, 0x4a, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x97, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xc8, 0x2a, 0xa9, 0x70, 0x09, 0xb8, 0xa7,
	0x96, 0x04, 0x67, 0xe6, 0xa5, 0xe7, 0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09,
	0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0xd6,
	0x5c, 0x82, 0x48, 0xaa, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0x95, 0x09, 0x89, 0x70, 0xb1,
	0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x4a, 0x4e,
	0x5c, 0x42, 0xee, 0xa9, 0x25, 0xbe, 0xa5, 0x39, 0x25, 0x99, 0x05, 0x78, 0x2c, 0x11, 0x92, 0xe2,
	0xe2, 0x28, 0x2c, 0x4d, 0xcc, 0x2b, 0xc9, 0x2c, 0xa9, 0x84, 0x1a, 0x00, 0xe7, 0x2b, 0xd9, 0x72,
	0x09, 0xa3, 0x98, 0x41, 0x8c, 0x13, 0x98, 0xe1, 0x4e, 0x30, 0x3a, 0xca, 0xc8, 0xc5, 0xeb, 0x58,
	0x5a, 0x92, 0xef, 0x09, 0x0b, 0x1b, 0xa1, 0x50, 0x2e, 0x4e, 0xb8, 0x8f, 0x84, 0x04, 0xf5, 0xd0,
	0xc3, 0x40, 0x4a, 0x48, 0x0f, 0xc3, 0xc3, 0x4a, 0x8a, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x92, 0x56,
	0x12, 0xd3, 0x07, 0x05, 0xb4, 0x2e, 0x3c, 0xa0, 0xf5, 0x8b, 0xc1, 0xea, 0xac, 0x18, 0xb5, 0x84,
	0x62, 0xb9, 0xb8, 0x91, 0xdc, 0x29, 0x24, 0xac, 0x87, 0xe9, 0x73, 0x29, 0x11, 0x3d, 0x2c, 0x5e,
	0x51, 0x52, 0x06, 0x1b, 0x2e, 0xab, 0x24, 0x81, 0x6e, 0x78, 0x2e, 0x54, 0xa5, 0x15, 0xa3, 0x56,
	0x12, 0x1b, 0x38, 0xd2, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x1c, 0x7e, 0x05, 0xea,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutoIncrementClient is the client API for AutoIncrement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoIncrementClient interface {
	GetSingle(ctx context.Context, in *GetSingleRequest, opts ...grpc.CallOption) (*GetSingleResponse, error)
	GetMultiple(ctx context.Context, in *GetMultipleRequest, opts ...grpc.CallOption) (*GetMultipleResponse, error)
}

type autoIncrementClient struct {
	cc *grpc.ClientConn
}

func NewAutoIncrementClient(cc *grpc.ClientConn) AutoIncrementClient {
	return &autoIncrementClient{cc}
}

func (c *autoIncrementClient) GetSingle(ctx context.Context, in *GetSingleRequest, opts ...grpc.CallOption) (*GetSingleResponse, error) {
	out := new(GetSingleResponse)
	err := c.cc.Invoke(ctx, "/AutoIncrement/GetSingle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoIncrementClient) GetMultiple(ctx context.Context, in *GetMultipleRequest, opts ...grpc.CallOption) (*GetMultipleResponse, error) {
	out := new(GetMultipleResponse)
	err := c.cc.Invoke(ctx, "/AutoIncrement/GetMultiple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoIncrementServer is the server API for AutoIncrement service.
type AutoIncrementServer interface {
	GetSingle(context.Context, *GetSingleRequest) (*GetSingleResponse, error)
	GetMultiple(context.Context, *GetMultipleRequest) (*GetMultipleResponse, error)
}

// UnimplementedAutoIncrementServer can be embedded to have forward compatible implementations.
type UnimplementedAutoIncrementServer struct {
}

func (*UnimplementedAutoIncrementServer) GetSingle(ctx context.Context, req *GetSingleRequest) (*GetSingleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingle not implemented")
}
func (*UnimplementedAutoIncrementServer) GetMultiple(ctx context.Context, req *GetMultipleRequest) (*GetMultipleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultiple not implemented")
}

func RegisterAutoIncrementServer(s *grpc.Server, srv AutoIncrementServer) {
	s.RegisterService(&_AutoIncrement_serviceDesc, srv)
}

func _AutoIncrement_GetSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoIncrementServer).GetSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AutoIncrement/GetSingle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoIncrementServer).GetSingle(ctx, req.(*GetSingleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoIncrement_GetMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoIncrementServer).GetMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AutoIncrement/GetMultiple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoIncrementServer).GetMultiple(ctx, req.(*GetMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoIncrement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AutoIncrement",
	HandlerType: (*AutoIncrementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSingle",
			Handler:    _AutoIncrement_GetSingle_Handler,
		},
		{
			MethodName: "GetMultiple",
			Handler:    _AutoIncrement_GetMultiple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto_increment.proto",
}
